### ISSUE TITLE
Wide review tracker

### ISSUE THREAD

**Issue by anssiko** [diekus/screen-fold#146]
### About

This is a process issue to track [wide review](https://www.w3.org/2023/Process-20231103/#wide-review) for the [Device Posture API](https://www.w3.org/TR/device-posture/).

An important part of wide review is horizontal review from W3C's [key horizontal groups](https://www.w3.org/Guide/documentreview/#how_to_get_horizontal_review) listed below in **horizontal groups** section. Also feedback from **other stakeholders** is equally important. Additional pointers are welcome via comments.

>Legend:
>⚪ Review request not submitted
>🟡 Review request submitted
>🔵 Review feedback received
>🟢 Review closed as completed

### Horizontal groups

🟢 ♿ **Accessibility**

- [x] Work through the <a rel="nofollow" class="external text" href="https://w3c.github.io/apa/fast/checklist.html">a11y checklist</a>
- [x] <a rel="nofollow" class="external text" href="https://github.com/w3c/a11y-request/issues/new/choose">Request a review via GitHub</a> from <a rel="nofollow" class="external text" href="https://www.w3.org/WAI/APA/">APA</a>: https://github.com/w3c/a11y-request/issues/84 completed https://github.com/w3c/a11y-request/issues/84#issuecomment-2150269320
  - [x] [Spec: Accessibility considerations](https://www.w3.org/TR/device-posture/#accessibility-considerations) based on APA WG contributions https://github.com/w3c/device-posture/issues/70 
  - [x] https://github.com/w3c/device-posture/issues/147

🟢 📐 **Architecture**

- [x] Ask the <a rel="nofollow" class="external text" href="https://www.w3.org/2001/tag/">TAG</a> for review; see <a rel="nofollow" class="external text" href="https://tag.w3.org/workmode/">how to work with the TAG</a>
   - [x] https://github.com/w3ctag/design-reviews/issues/575 completed Sep 2021
- See also related reviews:
   - [x] https://github.com/w3ctag/design-reviews/issues/689 completed Jun 2022
   - [x] https://github.com/w3ctag/design-reviews/issues/690 completed Mar 2022

🟢 🌍 **Internationalisation**

- [x] Read the <a rel="nofollow" class="external text" href="https://www.w3.org/International/review-request">Request a review</a> page
- [x] Work through the <a rel="nofollow" class="external text" href="https://www.w3.org/International/i18n-drafts/techniques/shortchecklist">i18n checklist</a>
- [x] <a rel="nofollow" class="external text" href="https://github.com/w3c/i18n-request/issues/new/choose">Request a review via GitHub</a>: https://github.com/w3c/i18n-request/issues/233
  - [x] https://github.com/w3c/device-posture/issues/148
  - [x] https://github.com/w3c/device-posture/issues/151

🟢 🔍 **Privacy**

- [x] Write a "Privacy Considerations" section for your document, taking into account the <a rel="nofollow" class="external text" href="https://www.w3.org/TR/security-privacy-questionnaire/">Self-Review Questionnaire: Security and Privacy</a>, <a rel="nofollow" class="external text" href="https://www.w3.org/TR/fingerprinting-guidance/">Mitigating Browser Fingerprinting in Web Specifications</a>, and <a rel="nofollow" class="external text" href="https://www.rfc-editor.org/rfc/rfc6973.html">RFC6973</a>
   - [x] [Self-Review Questionnaire self-assessment](https://github.com/w3c/device-posture/blob/gh-pages/security-privacy-self-assessment.md)
   - [x] [Spec: Privacy considerations](https://www.w3.org/TR/device-posture/#privacy-considerations)
- [x] <a rel="nofollow" class="external text" href="https://github.com/w3cping/privacy-request/issues/new/choose">Request a review via GitHub</a> from the <a rel="nofollow" class="external text" href="https://www.w3.org/Privacy/">Privacy Interest Group</a>: https://github.com/w3cping/privacy-request/issues/136

🟢 🔒 **Security**
- [x] Write a "Security Considerations" section for your document, taking into account the <a rel="nofollow" class="external text" href="https://www.w3.org/TR/security-privacy-questionnaire/">Self-Review Questionnaire: Security and Privacy</a>
   - [x] [Spec: Security considerations](https://www.w3.org/TR/device-posture/#security-considerations) status: no known security considerations, no security issues reported
   - [x] [Self-Review Questionnaire self-assessment](https://github.com/w3c/device-posture/blob/gh-pages/security-privacy-self-assessment.md)
- [x] <a rel="nofollow" class="external text" href="https://github.com/w3c/security-request/issues/new/choose">Request a review via GitHub</a>: https://github.com/w3c/security-request/issues/69
  - No concerns raised by 2024-08-31 deadline for comments

### Other stakeholders

From [who to ask for review](https://www.w3.org/Guide/documentreview/#who_to_ask_for_review):
>Horizontal reviews [...] are only a subset of a full wide review, which must also include other stakeholders including Web developers, technology providers and implementers not active in the Working Group, external groups and standards organizations working on related areas, etc.

- Mozilla position: https://github.com/mozilla/standards-positions/issues/882
- WebKit position: https://github.com/WebKit/standards-positions/issues/328

### Other resources

- [Origin trial for Foldable APIs](https://developer.chrome.com/blog/foldable-apis-ot) - explains how this JS API and CSS primitives work together
- [foldable-devices/demos](https://github.com/foldable-devices/demos) - demos of various use cases for the API

**Comment by anssiko** [comment]
@darktears can you produce a first stab of the responses to the [a11y checklist](https://w3c.github.io/apa/fast/checklist.html) and [i18n checklist](https://www.w3.org/International/i18n-drafts/techniques/shortchecklist) mentioned in this [wide review tracker](https://github.com/w3c/device-posture/issues/146#issue-2320708698)? We'll then review your first stabs with the WG, and I'll formally request respective reviews from horizontal groups when satisfied.

A good best practice has been to create a separate GH issue for each to allow reviewers follow-up as appropriate. See the recently completed wide reviews e.g. [this one](https://github.com/w3c/compute-pressure/issues?q=label%3Aw3c-process-steps+is%3Aclosed) and the [another one](https://github.com/w3c/deviceorientation/issues?q=label%3Aprocess+is%3Aclosed) to get an idea of expectations. Please also reuse and refer to the existing [accessibility considerations](https://www.w3.org/TR/device-posture/#accessibility-considerations) in your a11y checklist responses as appropriate.

Please let me know if you have any questions.

**Comment by darktears** [comment]
@anssiko done, please look.

**Comment by anssiko** [comment]
Thank you @darktears. I consider your a11y and i18n checklist contributions appropriate and note both already received comments. I have thus formally requested both the Accessibility and Internationalisation reviews to seek horizontal review from respective groups. Please be prepared to answer any questions from any of the horizontal groups in a timely manner.

I have also reflected this status in https://github.com/w3c/device-posture/issues/146#issue-2320708698

**Comment by anssiko** [comment]
I observed we also have all the materials expected by privacy and security reviewers, so I've also initiated both the Privacy and Security reviews today.

With that, all reviews are now either in flight or completed as reflected in https://github.com/w3c/device-posture/issues/146#issue-2320708698

I've asked reviewers to respond by the end of August 2024 latest. I'm expecting the editors to respond to any feedback, and as appropriate, attend focused sessions with horizontal groups to discuss specific considerations.

Thank you for your contributions, everyone.

**Comment by anssiko** [comment]
Accessibility review was just confirmed completed in https://github.com/w3c/a11y-request/issues/84#issuecomment-2150269320 🥳 

I've updated the tracker https://github.com/w3c/device-posture/issues/146#issue-2320708698 accordingly.

**Comment by anssiko** [comment]
As [discussed](https://www.w3.org/2024/09/24-dap-minutes.html#t32) at TPAC, @himorin will check with the privacy colleague to confirm PING review status https://github.com/w3cping/privacy-request/issues/136, after which we'll start a CfC to publish CR of Device Posture API.

@darktears @diekus @kenchris @rakuco and all the other contributors, thank you for your continued efforts in nudging this specification forward!

**Comment by himorin** [comment]
@darktears @diekus @kenchris @rakuco privacy-needs-resolution has been cleared : https://github.com/w3c/device-posture/issues/152
@anssiko Ready for CfC to publish as CRS (I don't think we have one before, e.g. to start this WR/HR, but please point if I missed something.)

**Comment by anssiko** [comment]
[CfC to publish Device Posture API Candidate Recommendation Snapshot - review by 8 Nov 2024](https://lists.w3.org/Archives/Public/public-device-apis/2024Nov/0000.html)

@himorin thank you for your support in making this publication happen.

**Comment by anssiko** [comment]
[This CfC passes](https://lists.w3.org/Archives/Public/public-device-apis/2024Nov/0002.html).

We will now proceed with the Device Posture API Candidate Recommendation Snapshot publication at the earliest opportunity. Congratulations to the group for this milestone. 🚀 

Thank you everyone for your contributions and to all the horizontal groups for careful review and comments.

@himorin will take care of the publication logistics, thank you!

I will close this wide review tracker to signal completion.
